config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'users/sign_up' => redirect('users/sign_in')
  devise_for :users, controllers: {
        registrations: 'registrations/registrations'
  }
  get "/dashboard" => "dashboard#index"
  get "/leaves/admin_index" => "leaves#admin_index"
  get "/leaves/:id/leave_decision" => "leaves#leave_decision"
  resources :leaves
  resources :notices
  resources :roles

  get "/leaves/:id/leave_status_accept" => "leaves#leave_status_accept"
  get "/leaves/:id/leave_status_decline" => "leaves#leave_status_decline"

  get "/list_users" => "list_users#index"
  get "/list_users/new" => "list_users#new"
  get "/list_users/:id/edit" => "list_users#edit"
  post "/list_users" => "list_users#create"
  put "/list_users/:id" => "list_users#update"
  delete "/list_users/:id" => "list_users#delete"
  delete "/list_users/:id/cancel" => "list_users#cancel"
  get "/checkins/checkin" => "checkins#checkin"
  get "/checkins/checkout" => "checkins#checkout"
  get "/my_notices" => "notices#my_notices"
  get "/list_users/:id/employee_leaves_checkinouts" => "list_users#employee_leaves_checkinouts"

  get "*path" => redirect("/404.html")

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  belongs_to :user
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  # before_action :set_checkin, only: [:show, :edit, :update, :destroy]

  # GET /checkins
  # GET /checkins.json

  def checkin
    if checked_in == false || checked_in == "recheck"
      @current_user_id = current_user.id
      @current_date = Date.today
      @checkin_time = Time.now
      @checkin = Checkin.new(user_id: @current_user_id, date: @current_date, check_in: @checkin_time)
      respond_to do |format|
        if @checkin.save
          format.js {}
        end
      end
    else
      redirect_to "/dashboard"
    end
  end

  def checkout
    if checked_in == true
      @current_user_id = current_user.id
      @current_date = Date.today
      @checked_in_user = Checkin.where(user_id: @current_user_id, date: @current_date).last
      @checkout_time = Time.now
      respond_to do |format|
        if @checked_in_user.update(check_out: @checkout_time)
          format.js {}
        end
      end
    else
      redirect_to "/dashboard"
    end
  end

  # def index
  #   @checkins = Checkin.all
  # end
  #
  # # GET /checkins/1
  # # GET /checkins/1.json
  # def show
  # end
  #
  # # GET /checkins/new
  # def new
  #   @checkin = Checkin.new
  # end
  #
  # # GET /checkins/1/edit
  # def edit
  # end
  #
  # # POST /checkins
  # # POST /checkins.json
  # def create
  #
  #   @checkin = Checkin.new(checkin_params)
  #
  #   respond_to do |format|
  #     if @checkin.save
  #       format.html { redirect_to @checkin, notice: 'Checkin was successfully created.' }
  #       format.json { render :show, status: :created, location: @checkin }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @checkin.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /checkins/1
  # # PATCH/PUT /checkins/1.json
  # def update
  #   respond_to do |format|
  #     if @checkin.update(checkin_params)
  #       format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @checkin }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @checkin.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /checkins/1
  # # DELETE /checkins/1.json
  # def destroy
  #   @checkin.destroy
  #   respond_to do |format|
  #     format.html { redirect_to checkins_url, notice: 'Checkin was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  #
  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_checkin
  #     @checkin = Checkin.find(params[:id])
  #   end
  #
  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def checkin_params
  #     params.require(:checkin).permit(:user_id, :date, :check_in, :check_out)
  #   end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
  # Checks if the current user checked in today.
  def checked_in
    @current_user_id = current_user.id
    @current_date = Date.today
    @checked_in_user = Checkin.where(user_id: @current_user_id, date: @current_date).last
    if @checked_in_user != nil && @checked_in_user.check_in != nil && @checked_in_user.check_out != nil
      return "recheck"
    elsif @checked_in_user != nil && @checked_in_user.check_in != nil && @checked_in_user.check_out == nil
      return true
    else
      return false
    end
  end
end

app/views/checkins/_checkin.html.erb
<li class="bg-red dropdown messages-menu" id="check_out">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" onclick="checkout()">
    <i class="fa fa-flag-o" style="padding-right: 10px; padding-left: 10px;"><strong> Check out</strong></i>
  </a>
</li>

app/views/checkins/_checkout.html.erb
<li class="bg-green dropdown messages-menu" id="check_in">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" onclick="checkin()">
    <i class="fa fa-thumbs-o-up" style="padding-right: 10px; padding-left: 10px;"><strong> Check in</strong></i>
  </a>
</li>

app/views/checkins/_form.html.erb
<%= form_for(@checkin) do |f| %>
  <% if @checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% @checkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :check_in %><br>
    <%= f.datetime_select :check_in %>
  </div>
  <div class="field">
    <%= f.label :check_out %><br>
    <%= f.datetime_select :check_out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkins/checkin.js.erb
$('#check_in').remove();
$('#get-li').prepend("<%= escape_javascript (render 'checkin') %>");

app/views/checkins/checkout.js.erb
$('#check_out').remove();
$('#get-li').prepend("<%= escape_javascript (render 'checkout') %>");

app/views/checkins/edit.html.erb
<h1>Editing Checkin</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Checkins</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Check in</th>
      <th>Check out</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= checkin.user_id %></td>
        <td><%= checkin.date %></td>
        <td><%= checkin.check_in %></td>
        <td><%= checkin.check_out %></td>
        <td><%= link_to 'Show', checkin %></td>
        <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
        <td><%= link_to 'Destroy', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkin', new_checkin_path %>

app/views/checkins/new.html.erb
<h1>New Checkin</h1>

<%= render 'form' %>

<%= link_to 'Back', checkins_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @checkin.user_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @checkin.date %>
</p>

<p>
  <strong>Check in:</strong>
  <%= @checkin.check_in %>
</p>

<p>
  <strong>Check out:</strong>
  <%= @checkin.check_out %>
</p>

<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>