config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'users/sign_up' => redirect('users/sign_in')
  devise_for :users, controllers: {
        registrations: 'registrations/registrations'
  }
  get "/dashboard" => "dashboard#index"
  get "/leaves/admin_index" => "leaves#admin_index"
  get "/leaves/:id/leave_decision" => "leaves#leave_decision"
  resources :leaves
  resources :notices
  resources :roles

  get "/leaves/:id/leave_status_accept" => "leaves#leave_status_accept"
  get "/leaves/:id/leave_status_decline" => "leaves#leave_status_decline"

  get "/list_users" => "list_users#index"
  get "/list_users/new" => "list_users#new"
  get "/list_users/:id/edit" => "list_users#edit"
  post "/list_users" => "list_users#create"
  put "/list_users/:id" => "list_users#update"
  delete "/list_users/:id" => "list_users#delete"
  delete "/list_users/:id/cancel" => "list_users#cancel"
  get "/checkins/checkin" => "checkins#checkin"
  get "/checkins/checkout" => "checkins#checkout"
  get "/my_notices" => "notices#my_notices"
  get "/list_users/:id/employee_leaves_checkinouts" => "list_users#employee_leaves_checkinouts"

  get "*path" => redirect("/404.html")

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

  <%= csrf_meta_tags %>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="<%= admin? ? "/dashboard" : "/notices" %>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>Chutti</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Chutti</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav" id="get-li">
          <!-- Check in checkout -->
          <% if !checked_in || checked_in == "recheck" %>
            <li class="bg-green dropdown messages-menu" id="check_in">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" onclick="checkin()">
                <i class="fa fa-thumbs-o-up" style="padding-right: 10px; padding-left: 10px;"><strong> Check in</strong></i>
              </a>
            </li>
          <% else %>
            <li class="bg-red dropdown messages-menu" id="check_out">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" onclick="checkout()">
                <i class="fa fa-flag-o" style="padding-right: 10px; padding-left: 10px;"><strong> Check out</strong></i>
              </a>
            </li>
          <% end %>
          <!-- Messages: style can be found in dropdown.less-->

          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="<%= current_user.image.url %>" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs"><%= current_user.name%></span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="<%= current_user.image.url %>" class="img-circle" alt="User Image">

                <p>
                  <%= current_user.name%></br>
                  <%= current_user.email%>
                </p>
              </li>
              <!-- Menu Body -->
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <%= link_to('Profile', "/list_users/#{current_user.id}/edit", :class=> "btn btn-default btn-flat") %>
                  <!-- <a href="#" class="btn btn-default btn-flat">Profile</a> -->
                </div>
                <div class="pull-right">
                  <%= link_to('Sign out', destroy_user_session_path, :method => :delete, :class=> "btn btn-default btn-flat") %>
                  <!-- <a href="#" class="btn btn-default btn-flat">Sign out</a> -->
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <!-- <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li> -->
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <!-- <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image"> -->
          <img src="<%= current_user.image.url %>" class="img-circle" alt="User Image">
          <!-- <#%= image_tag current_user.image.thumb('160x160#').url if current_user.image_stored? %> -->
        </div>
        <div class="pull-left info">
          <p><%= current_user.name%></p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header">MENU</li>
        <% if admin?%>
          <li class="<%= 'active' if params[:controller] == 'dashboard' %>"><a href="<%= "/dashboard"%>"><i class="glyphicon glyphicon-list-alt"></i> <span>Dashboard</span></a></li>
        <% end%>
        <li class="<%= 'active' if (params[:controller] == 'notices' && params[:action] == 'index')%>"><a href="/notices"><i class="glyphicon glyphicon-pushpin"></i> <span>Notice Board</span></a></li>
        <!-- Optionally, you can add icons to the links -->
        <!-- <li class="<%= 'active' if (params[:controller] == 'notices' && params[:action] == 'new')%>"><a href="/notices/new"><i class="glyphicon glyphicon-edit"></i> <span>Add Notice</span></a></li> -->
        <% if !admin?%>
          <li class="<%= 'active' if params[:controller] == 'leaves' && params[:action] == 'index'%>"><a href="/leaves"><i class="glyphicon glyphicon-list-alt"></i> <span>List of Leaves</span></a></li>
        <% end%>
        <% if admin?%>
          <li class="<%= 'active' if params[:controller] == 'leaves' %>"><a href="<%=leaves_admin_index_path%>"><i class="glyphicon glyphicon-list-alt"></i> <span>List Of Leaves</span></a></li>
        <% end%>
        <% if admin?%>
          <!-- <li class="<%= 'active' if (params[:controller] == 'list_users' && params[:action] == 'new')%>" ><a href="/list_users/new"><i class="glyphicon glyphicon-plus-sign"></i> <span>Add New Employee</span></a></li> -->
          <li class="<%= 'active' if (params[:controller] == 'list_users' && params[:action] == 'index')%>" ><a href="/list_users"><i class="glyphicon glyphicon-sort-by-alphabet"></i> <span>Employee List</span></a></li>
          <li class="<%= 'active' if (params[:controller] == 'roles' && params[:action] == 'index')%>" ><a href="/roles"><i class="glyphicon glyphicon-sort-by-attributes-alt"></i> <span>Roles</span></a></li>
        <%end%>
          <li class="<%= 'active' if (params[:controller] == 'notices' && params[:action] == 'my_notices')%>" ><a href="/my_notices"><i class="glyphicon glyphicon-share"></i> <span>My Notices</span></a></li>

          <!-- <%= link_to('Sign out', destroy_user_session_path, :method => :delete, :class=> "btn btn-default btn-flat") %> -->
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    <!-- Main content -->
    <section class="content" >
      <!-- Your Page Content Here -->
        <%= yield %>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <!-- <div class="pull-right hidden-xs">
      Anything you want
    </div> -->
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

  <%= csrf_meta_tags %>
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Welcome</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <!-- <form action="../../index2.html" method="post">
      <div class="form-group has-feedback">
        <input type="email" class="form-control" placeholder="Email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div> -->
        <!-- /.col -->
        <!-- <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div> -->
        <!-- /.col -->
      <!-- </div>
    </form> -->
    <%= yield %>
    <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
    </div>
    <!-- /.social-auth-links -->

    <!-- <a href="#">I forgot my password</a><br>
    <a href="register.html" class="text-center">Register a new membership</a> -->

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>